
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bloom_explorer_db
      POSTGRES_USER: androidev
      POSTGRES_PASSWORD: securepass84
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
